// Per-user compiler environment — generated by koruc.
// Flags + env vars baked from the CLI invocation that produced this directory.

const std = @import("std");

pub const CompilerEnv = struct {
    /// Default emission target language (--lang=<name>)
    pub const lang: []const u8 = "zig";

    /// All compiler flags (for runtime checking)
    pub const flags = &[_][]const u8{
        "build=macos",
    };

    /// Check if a compiler flag is set (comptime)
    pub fn hasFlag(comptime name: []const u8) bool {
        inline for (flags) |flag| {
            if (std.mem.eql(u8, name, flag)) return true;
        }
        return false;
    }

    /// Check if a compiler flag is set (runtime)
    pub fn hasFlagRuntime(name: []const u8) bool {
        for (flags) |flag| {
            if (std.mem.eql(u8, name, flag)) return true;
        }
        return false;
    }

    /// Get environment variable value
    pub fn getEnv(comptime key: []const u8) ?[]const u8 {
        _ = key;
        return null;
    }
};
