// The Vercel adapter for a Koru/Orisha wasm reactor. Generated by koru-vercel
// build from your site's declared surface; everything platform-specific lives
// here, and it is deliberately thin.
//
// The surface, in order of precedence:
//   1. Genuinely live paths (__DYNAMIC__) reverse-proxy to the backend.
//   2. Declared client-only routes (__CLIENT_ROUTES__) get the SPA shell —
//      a designed state for real routes, never a catch-all.
//   3. Baked static files answer from the reactor.
//   4. Everything else is a real 404 from the reactor.
//
// The module is instantiated at module scope — once per cold start, not once
// per request.
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

// The one import the Orisha reactor needs: a host clock for its Date/ETag
// headers. It is an i64 wasm import, so the JS side must return a BigInt —
// a Number throws "Cannot convert X to a BigInt" the first time a GENERATED
// response (a real 404) asks for a Date header. Static pre-rendered responses
// never call it, which is how a Number shim could sit in a deployed adapter
// unnoticed until a 404 needed a date.
const env = { time: () => BigInt(Math.floor(Date.now() / 1000)) };

const ready = (async () => {
  const bytes = await readFile(join(here, "..", "wasm", "handler.wasm"));
  const { instance } = await WebAssembly.instantiate(bytes, { env });
  return instance.exports;
})();

const encoder = new TextEncoder();

// --- site surface, declared at build time -------------------------------
const CLIENT_ROUTES = __CLIENT_ROUTES_JSON__; // null | string[]
const FALLBACK_PATH = __FALLBACK_PATH__; // null | "/200.html"
const DYNAMIC_PREFIXES = __DYNAMIC_JSON__; // null | string[]
const BACKEND = __BACKEND__; // null | string

// Split a raw HTTP response into the parts Vercel needs. The module owns the
// status line and the headers, so this only re-shapes what it already said.
function parseRawResponse(buffer) {
  const separator = buffer.indexOf("\r\n\r\n");
  const head = buffer.subarray(0, separator).toString("latin1").split("\r\n");
  const body = buffer.subarray(separator + 4);
  const status = Number(head[0].split(" ")[1]);
  const headers = {};
  for (const line of head.slice(1)) {
    const at = line.indexOf(":");
    headers[line.slice(0, at).trim()] = line.slice(at + 1).trim();
  }
  return { status, headers, body };
}

async function answerFromReactor(wasm, target) {
  const rawRequest = encoder.encode(`GET ${target} HTTP/1.1\r\nHost: korulang.org\r\n\r\n`);
  if (rawRequest.length > wasm.request_cap()) return { status: 414, headers: {}, body: Buffer.alloc(0) };
  // Re-read memory.buffer per request — growing a wasm memory detaches every
  // view taken before the growth, and a stale view reads zeroes silently.
  new Uint8Array(wasm.memory.buffer).set(rawRequest, wasm.request_ptr());
  const written = wasm.handle(rawRequest.length);
  if (written === 0) return { status: 500, headers: {}, body: Buffer.alloc(0) };
  const start = wasm.response_ptr();
  const raw = Buffer.from(wasm.memory.buffer.slice(start, start + written));
  return parseRawResponse(raw);
}

export default async function handler(req, res) {
  const { pathname, search } = new URL(req.url, "http://localhost");

  // 1. Genuinely live surface → the backend, the same way it would be asked
  //    today. Nothing here decides codes or content types.
  if (DYNAMIC_PREFIXES && DYNAMIC_PREFIXES.some((p) => pathname.startsWith(p))) {
    const url = new URL(pathname + search, BACKEND);
    const upstream = await fetch(url, {
      method: req.method,
      headers: {
        "user-agent": req.headers["user-agent"] ?? "orisha-hybrid",
        cookie: req.headers["cookie"] ?? "",
        "content-type": req.headers["content-type"] ?? "",
      },
      body: ["GET", "HEAD"].includes(req.method) ? undefined : req,
    });
    const body = Buffer.from(await upstream.arrayBuffer());
    res.statusCode = upstream.status;
    for (const [name, value] of upstream.headers) {
      if (["transfer-encoding", "connection", "keep-alive"].includes(name.toLowerCase())) continue;
      res.setHeader(name, value);
    }
    return res.end(body);
  }

  const wasm = await ready;

  // 2. Declared client-only routes → the shell. A client route is a whole
  //    subtree that hydrates from the shell, so its ROOT and every path below
  //    it must serve the shell — an exact-root match would break every deep
  //    link and crawler hit. The shell is still never a sweep for "anything
  //    not found": only DECLARED client routes get it, everything else falls
  //    through to the reactor, which answers 404 for paths the site does not
  //    have.
  const target =
    CLIENT_ROUTES && CLIENT_ROUTES.some((r) => pathname === r || pathname.startsWith(r + "/"))
      ? FALLBACK_PATH
      : pathname;

  const { status, headers, body } = await answerFromReactor(wasm, target);
  res.statusCode = status;
  for (const [name, value] of Object.entries(headers)) res.setHeader(name, value);
  res.end(body);
}
